version: '3'

services:

  ghost:
    container_name: container-da-tiemi
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - db
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    networks:
      - my-network

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      # - MYSQL_ROOT_PASSWORD=password #sintaxe em string
      MYSQL_ROOT_PASSWORD: password
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network: